#!/usr/bin/env bash
#/redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/paulinemutuku permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
      
sudo service nginx restart
